# Exercise - Numpy

1) Import NumPy package

In [8]:
import numpy as np
import random as rand

2) Create a list of size 10 with all zeros

In [4]:
# test_array = np.zeros(10)
test_array = np.full(10, 0)
test_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

3) Create a 3 X 3 Matrix with values ranging from 0 to 8

In [30]:
a = np.random.randint(0, 9, size=9)
a = a.reshape(3,3)
a

array([[0, 0, 5],
       [2, 3, 0],
       [7, 5, 8]], dtype=int32)

4) Create a 3 X 3 X 3 array with random values 

In [31]:
a = np.random.randint(0, 100, size=27)
a = a.reshape(3,3,3)
a

array([[[73, 92, 72],
        [23,  1, 58],
        [98, 87, 84]],

       [[ 3,  4, 68],
        [32, 70, 70],
        [42, 89,  6]],

       [[54, 16, 94],
        [15,  6, 33],
        [89, 17, 57]]], dtype=int32)

5) Create a 5 X 5 array with random values.  Find the minimum and maximum values.

In [64]:
a = np.random.randint(1, 100, size=25)
a = a.reshape(5,5)
print(a)
print("min: {} max: {}".format(a.min(), a.max()))

[[77 80  2 39 41]
 [58 42  2  8 96]
 [68 88 59 91 16]
 [ 4 23 83 26 50]
 [53 32 64  6 59]]
min: 2 max: 96


6) Create an array of 10 random values.  Rearrange the arrange in order.

In [68]:
a = np.random.randint(1, 100, 10)
a.sort()
a

array([21, 26, 32, 36, 39, 41, 49, 69, 71, 82], dtype=int32)

7) Create an array of 10 random values.  Get the sum and average value of the elements.

In [84]:
a = np.random.randint(1, 100, 10)
sum = a.sum()
average = np.average(a)
print(a)
print(sum)
print(average)

[27 23 41 73 34 85 77 36 16 37]
449
44.9
